### ISSUE TITLE
希望能出EPUB的版本

### ISSUE THREAD

**Issue by lon91ong** [wklchris/Note-by-LaTeX#12]
如题，pdf的排版太严格，没有epub灵活方便

**Comment by wklchris** [comment]
LaTeX 没有完美的转换 epub 方案，或者说当今 LaTeX 编译的唯一目标就是将文档编译为 pdf 格式。

由于本项目的源 tex 文件都是公开的，读者如果需要其他格式，可以自行搜索和使用工具来进行转换。相关的曲线迂回工具应该还是有的，但我并没有使用过。举例说明，你可以参考：[Use LaTeX to produce Epub - LaTeX Stack Exchange](https://tex.stackexchange.com/questions/1551/use-latex-to-produce-epub) 这篇问答中的方案进行尝试。
