### ISSUE TITLE
行内 tcbox 环境的竖直位置问题

### ISSUE THREAD

**Issue by qiuzhu** [wklchris/Note-by-LaTeX#6]
老是感觉\pkg定义的colorbox命令生成的效果，使得基线不对齐，有种往下的感觉，就是那种比周围的汉字低那么一点，请确认调教下

**Comment by wklchris** [comment]
@qiuzhu 这恰恰因为**文中是按基线对齐、而不是竖直居中对齐**的．你所说的“低”或者“高”，实质上描述的是 colorbox 的位置、而不是英文文字的位置．

这是中英文混排不可避免的，但文中的排版方法的确没有问题．box 的视觉问题在 `\pkg`，`\envi` 以及 `\latexline` 命令中都是一样．原因在于不同字母的高度和深度并不一样；但是汉字的高度却可以认为是不变的．

比如字母 “p”，在基线以上的高度很小，在基线以下的深度却较大，这就会导致 tcolorbox 的竖直中轴线靠下，比周围的汉字的竖直中轴线要低 —— 除非这个 package 或 environment 的名称中还有一个比较“高”的字母（比如 “h”），让它的高度与 “p” 的深度相平衡，这样才显得 tcolorbox 的竖直居中对齐了．

总之，排版是正确的，但是视觉上可能会有奇怪之处．目前没有应对方案．
