### ISSUE TITLE
66.67.71页有三处引用失效

### ISSUE THREAD

**Issue by happyTonakai** [wklchris/Note-by-LaTeX#7]
1.6.4 release中，在66页末尾、67页开头和71页末尾有三处引用失效，搜索 `??` 就可以快速找到

**Comment by wklchris** [comment]
该问题已由 4d47aeaed9c13264c872e2ad9c19334e777f225b commit 更正。

*注：1.6.4 目前仍是 pre-release，而不是正式的 release。在正式 release 前，仍可能包含其他问题。请读者谨慎下载。*
